// config/ckeditor.ts
import {
  ClassicEditor,
  Essentials,
  Paragraph,
  Heading,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  Link,
  List,
  TodoList,
  BlockQuote,
  Alignment,
  Indent,
  IndentBlock,
  Font,
  FontFamily,
  FontSize,
  FontColor,
  FontBackgroundColor,
  Highlight,
  Code,
  CodeBlock,
  Table,
  TableToolbar,
  TableProperties,
  TableCellProperties,
  Image,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageCaption,
  MediaEmbed,
  HorizontalLine,
  SpecialCharacters,
  SpecialCharactersEssentials,
  FindAndReplace,
  RemoveFormat,
  SourceEditing,
} from "ckeditor5";

export { ClassicEditor };

export const editorConfig = {
  licenseKey: "GPL",
  plugins: [
    Essentials,
    Paragraph,
    Heading,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Subscript,
    Superscript,
    Link,
    List,
    TodoList,
    BlockQuote,
    Alignment,
    Indent,
    IndentBlock,
    Font,
    FontFamily,
    FontSize,
    FontColor,
    FontBackgroundColor,
    Highlight,
    Code,
    CodeBlock,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    Image,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageCaption,
    MediaEmbed,
    HorizontalLine,
    SpecialCharacters,
    SpecialCharactersEssentials,
    FindAndReplace,
    RemoveFormat,
    SourceEditing,
  ],
  toolbar: {
    items: [
      "heading",
      "|",
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "subscript",
      "superscript",
      "|",
      "fontFamily",
      "fontSize",
      "fontColor",
      "fontBackgroundColor",
      "highlight",
      "|",
      "alignment",
      "|",
      "bulletedList",
      "numberedList",
      "todoList",
      "outdent",
      "indent",
      "|",
      "link",
      "insertImage",
      "insertTable",
      "mediaEmbed",
      "blockQuote",
      "codeBlock",
      "code",
      "horizontalLine",
      "specialCharacters",
      "|",
      "findAndReplace",
      "removeFormat",
      "sourceEditing",
      "|",
      "undo",
      "redo",
    ],
    shouldNotGroupWhenFull: true,
  },
  heading: {
    options: [
      { model: "paragraph", title: "Paragraph", class: "ck-heading_paragraph" },
      { model: "heading1", view: "h1", title: "Heading 1", class: "ck-heading_heading1" },
      { model: "heading2", view: "h2", title: "Heading 2", class: "ck-heading_heading2" },
      { model: "heading3", view: "h3", title: "Heading 3", class: "ck-heading_heading3" },
      { model: "heading4", view: "h4", title: "Heading 4", class: "ck-heading_heading4" },
    ],
  },
  fontFamily: {
    options: [
      "default",
      "Arial, Helvetica, sans-serif",
      "Georgia, serif",
      "Times New Roman, Times, serif",
      "Courier New, Courier, monospace",
      "Verdana, Geneva, sans-serif",
    ],
  },
  fontSize: {
    options: ["tiny", "small", "default", "big", "huge"],
  },
  image: {
    toolbar: [
      "imageStyle:block",
      "imageStyle:side",
      "|",
      "toggleImageCaption",
      "imageTextAlternative",
      "|",
      "resizeImage",
    ],
    resizeOptions: [
      { name: "resizeImage:original", value: null, label: "Original" },
      { name: "resizeImage:25", value: "25", label: "25%" },
      { name: "resizeImage:50", value: "50", label: "50%" },
      { name: "resizeImage:75", value: "75", label: "75%" },
    ],
  },
  table: {
    contentToolbar: [
      "tableColumn",
      "tableRow",
      "mergeTableCells",
      "tableProperties",
      "tableCellProperties",
    ],
  },
  codeBlock: {
    languages: [
      { language: "plaintext", label: "Plain text" },
      { language: "javascript", label: "JavaScript" },
      { language: "typescript", label: "TypeScript" },
      { language: "python", label: "Python" },
      { language: "html", label: "HTML" },
      { language: "css", label: "CSS" },
      { language: "sql", label: "SQL" },
      { language: "json", label: "JSON" },
      { language: "bash", label: "Bash" },
    ],
  },
};